import type { PayarchDiagram } from '../index';

const stepsOrder = [
  'consumer-intent',
  'tap-validation',
  'tap-credential-issued',
  'merchant-accepts',
  'acquirer-iso8583',
  'visanet-routes',
  'issuer-auth',
  'settlement-complete',
];

const step = (
  stepId: string,
  business: string,
  technical: string,
  iso8583?: string,
  active = false,
  outgoingEdge?: string,
  incomingEdge?: string,
) => ({
  stepId,
  active,
  outgoingEdge,
  incomingEdge,
  layerText: { business, technical, iso8583 },
});

export const agenticCheckoutE2E: PayarchDiagram = {
  id: 'agentic-checkout-e2e',
  title: 'Agentic Checkout - Public Architecture Map',
  description:
    'Conceptual end-to-end map for an agent-assisted card checkout using public Visa Intelligent Commerce and Trusted Agent Protocol material. Field-level rail mappings, private data elements, headers, credential formats, response codes, and latency targets are intentionally left illustrative unless public specifications document them.',
  version: '2.0.0-public',
  protocol: 'Visa Intelligent Commerce + Trusted Agent Protocol',
  settlementCycle: 'existing card-clearing cycle',
  stepsOrder,

  nodes: [
    {
      id: 'n-agent-runtime',
      type: 'AgentRuntime',
      position: { x: 40, y: 60 },
      data: {
        label: 'AI Agent',
        sublabel: 'agent runtime',
        layer: 'agent',
        vendor: ['AI assistant', 'agent platform', 'merchant tools'],
        properties: {
          runtime: 'LLM + tool executor',
          identity_protocol: 'HTTP Message Signatures via TAP',
          trigger: 'natural language intent',
          tool_calls: ['browse catalog', 'prepare checkout', 'request scoped payment credential', 'receive authorization result'],
        },
        steps: {
          'consumer-intent': step(
            'consumer-intent',
            'The consumer gives the agent a shopping intent and any relevant constraints. The agent resolves the product, merchant, and price before payment begins.',
            'The agent turns natural-language intent into structured checkout context: merchant, amount, item, currency, and policy constraints. This is application-layer logic, not a card-network message.',
            '// No ISO 8583 message yet\n// Application context: merchant, amount, item, currency, policy',
            true,
            'e-agent-to-tap',
          ),
          'tap-validation': step(
            'tap-validation',
            'The agent proves that a registered key signed the request. This step is about agent identity and request freshness, not payment authorization.',
            'A verifier reconstructs the RFC 9421 signature base, checks the public key, validates freshness and replay controls, and applies policy for the requested action.',
            '// HTTP-layer verification only\n// Public material does not publish a Visa production endpoint, header contract, or credential format.',
          ),
          'merchant-accepts': step(
            'merchant-accepts',
            'The agent submits checkout context to the merchant after the trust layer has enough evidence to treat it as an approved agent flow.',
            'The merchant or edge verifier can use the TAP result as a trust signal before creating an order and starting the payment leg.',
            '// Merchant payment request begins after order creation\n// Exact merchant integration is implementation-specific.',
            true,
            'e-agent-to-merchant',
          ),
          'settlement-complete': step(
            'settlement-complete',
            'The agent receives the merchant outcome and reports the result to the consumer. Settlement follows the normal card lifecycle.',
            'The completion event can be logged for support and dispute context, but public Visa material does not define a mandatory outcome-reporting API shape.',
            '// Outcome notification to consumer and merchant systems\n// Clearing/settlement timing depends on the existing payment path.',
            true,
          ),
        },
      },
    },
    {
      id: 'n-agent-wallet',
      type: 'AgentWallet',
      position: { x: 40, y: 220 },
      data: {
        label: 'Scoped Credential',
        sublabel: 'tokenized card credential',
        layer: 'agent',
        vendor: ['Visa Token Service', 'issuer bank'],
        properties: {
          token_type: 'network token or virtual credential',
          spend_limit: 'consumer-configured',
          categories: ['merchant/category policy'],
          expiry: 'implementation-specific',
          passkey_bound: true,
          pan_exposure: 'tokenized credential only',
          provisioning: 'passkey-backed enrollment or step-up',
        },
        steps: {
          'consumer-intent': step(
            'consumer-intent',
            'Before checkout, the consumer has authorized the agent to use a constrained payment credential or payment instruction.',
            'Public Visa descriptions support tokenized credentials, passkeys, and consumer control. They do not publish a complete production credential payload for every exchange.',
            '// Credential setup is outside the authorization message\n// Scope: consumer, agent, merchant/amount policy',
            true,
            'e-wallet-to-tap',
          ),
          'tap-validation': step(
            'tap-validation',
            'The trust layer can take payment scope into account before allowing the agent to continue.',
            'The verifier can compare the signed request with policy context such as merchant, amount, and allowed action. Exact claim names are not public specifications.',
            '// Policy context can inform the verifier\n// Exact field names are illustrative.',
            true,
          ),
          'acquirer-iso8583': step(
            'acquirer-iso8583',
            'A tokenized credential, not the raw card number, is what should move into payment processing.',
            'The merchant or PSP submits a payment request using the scoped credential. The exact credential exchange and acquirer mapping depend on the implementation.',
            '// Authorization can carry tokenized credential data\n// Exact Visa field assignments are not public.',
            true,
          ),
          'issuer-auth': step(
            'issuer-auth',
            'The issuer can evaluate the transaction against consumer controls and normal authorization policy.',
            'Policy checks can include amount, merchant, token status, authentication history, risk, and available funds.',
            '// Issuer/network response codes are implementation-specific.',
            true,
          ),
        },
      },
    },
    {
      id: 'n-tap',
      type: 'TrustedAgentProtocol',
      position: { x: 380, y: 60 },
      data: {
        label: 'Trusted Agent Protocol',
        sublabel: 'RFC 9421 signatures',
        layer: 'trust',
        vendor: ['Visa', 'Cloudflare'],
        properties: {
          standard: 'HTTP Message Signatures (RFC 9421)',
          algorithm: 'Ed25519 in public examples',
          key_directory: 'agent public-key registry',
          replay_protection: 'timestamp and nonce checks',
        },
        steps: {
          'tap-validation': step(
            'tap-validation',
            'TAP verifies that the request came from a registered agent key and that the signed request has not been replayed.',
            'Public TAP material shows signed HTTP requests, key lookup, freshness checks, nonce handling, and request-tag validation. Production cache lifetimes, headers, and exact verdict formats are not public facts.',
            '// HTTP signature verification\n// Not a payment authorization message.',
            true,
            'e-tap-validates',
            'e-agent-to-tap',
          ),
          'tap-credential-issued': step(
            'tap-credential-issued',
            'If verification succeeds, the agent can proceed with a trust result or scoped proof accepted by the merchant integration.',
            'This diagram intentionally avoids naming a concrete Visa-issued bearer credential, lifetime, or private header because those details are not published as TAP production specifications.',
            '// Trust result/proof format: implementation-specific.',
            true,
            'e-tap-to-merchant',
          ),
        },
      },
    },
    {
      id: 'n-visa',
      type: 'VisaIntelligentCommerce',
      position: { x: 380, y: 220 },
      data: {
        label: 'Visa Intelligent Commerce',
        sublabel: 'tokens + agent services',
        layer: 'network',
        vendor: ['Visa'],
        properties: {
          platform: 'Visa Intelligent Commerce',
          token_service: 'Visa Token Service',
          mcp_server: 'Visa public AI examples',
        },
        steps: {
          'visanet-routes': step(
            'visanet-routes',
            'The card network path can route the transaction and preserve relevant token and authorization context.',
            'Public sources support the concept of tokenized credentials and agent trust signals. They do not publish a complete public ISO 8583 mapping for agentic transactions.',
            '// Authorization metadata can travel through existing rails\n// Exact data elements, private fields, and response codes are not public.',
            true,
            'e-visa-to-issuer',
            'e-acquirer-to-visa',
          ),
          'settlement-complete': step(
            'settlement-complete',
            'The transaction remains on familiar card rails after authorization.',
            'Clearing, settlement, refunds, and disputes still depend on the existing card-network, acquirer, issuer, and merchant systems.',
            '// Settlement follows existing network and issuer processes.',
            true,
          ),
        },
      },
    },
    {
      id: 'n-merchant',
      type: 'Merchant',
      position: { x: 40, y: 520 },
      data: {
        label: 'Merchant',
        sublabel: 'checkout + PSP integration',
        layer: 'payment',
        vendor: ['merchant', 'PSP'],
        properties: {
          tap_integration: 'edge or backend verification',
          bot_protection: 'agent identity and request integrity',
          consumer_recognition: 'merchant-defined returning-customer logic',
        },
        steps: {
          'merchant-accepts': step(
            'merchant-accepts',
            'The merchant accepts the checkout request, creates the order, and starts the payment request through its PSP or acquirer.',
            'TAP helps separate approved agent traffic from unknown automation. Merchant order creation and consumer recognition remain merchant implementation details.',
            '// Order created\n// PSP/acquirer payment request starts here.',
            true,
            'e-merchant-to-acquirer',
            'e-agent-to-merchant',
          ),
        },
      },
    },
    {
      id: 'n-acquirer',
      type: 'Acquirer',
      position: { x: 210, y: 680 },
      data: {
        label: 'Acquirer / PSP',
        sublabel: 'existing card path',
        layer: 'payment',
        vendor: ['acquirer', 'PSP'],
        properties: {
          key_modifications: 'tokenized credential and authorization metadata',
          connection: 'existing acquirer/card-network path',
          message_encryption: 'network-specific transport controls',
        },
        steps: {
          'acquirer-iso8583': step(
            'acquirer-iso8583',
            'The PSP or acquirer turns the merchant payment request into a network authorization request.',
            'The safe public claim is that token and agent context can become authorization metadata. Exact data elements and values are network/private specifications.',
            '// Existing authorization request\n// Token + context metadata, field mapping not publicly specified.',
            true,
            'e-acquirer-to-visa',
            'e-merchant-to-acquirer',
          ),
        },
      },
    },
    {
      id: 'n-issuer',
      type: 'Issuer',
      position: { x: 420, y: 520 },
      data: {
        label: 'Issuer',
        sublabel: 'authorization decision',
        layer: 'payment',
        vendor: ['issuer bank'],
        properties: {
          decision_factors: ['available funds', 'risk controls', 'token status', 'consumer policy'],
          passkey_validation: 'may be part of enrollment or instruction creation',
          response_time: 'not publicly specified',
        },
        steps: {
          'issuer-auth': step(
            'issuer-auth',
            'The issuer decides whether to approve the transaction using normal authorization logic plus any token or policy context available to it.',
            'This is where issuer risk, consumer controls, token lifecycle, and available funds matter. Public sources do not define an agentic approval code or decline code.',
            '// Authorization response returns through existing rails\n// Approval and decline codes are implementation-specific.',
            true,
            'e-issuer-to-visa',
            'e-visa-to-issuer',
          ),
        },
      },
    },
  ],

  edges: [
    {
      id: 'e-agent-to-tap',
      source: 'n-agent-runtime',
      target: 'n-tap',
      type: 'intent',
      animated: true,
      label: 'signed request',
      activeInSteps: ['consumer-intent', 'tap-validation'],
      data: {
        protocol: 'HTTPS + HTTP Message Signatures',
        payload: 'covered request components, key identifier, timestamp, nonce, tag',
        direction: 'agent -> verifier',
      },
    },
    {
      id: 'e-wallet-to-tap',
      source: 'n-agent-wallet',
      target: 'n-tap',
      type: 'intent',
      animated: true,
      label: 'payment scope',
      activeInSteps: ['consumer-intent', 'tap-validation'],
      data: {
        protocol: 'implementation-specific context',
        payload: 'consumer authorization and scoped credential reference',
        direction: 'credential context -> verifier',
      },
    },
    {
      id: 'e-tap-validates',
      source: 'n-tap',
      target: 'n-visa',
      type: 'tap-credential',
      animated: true,
      label: 'trust check',
      activeInSteps: ['tap-validation', 'tap-credential-issued'],
      data: {
        protocol: 'TAP policy/verifier flow',
        payload: 'agent identity, request freshness, allowed action',
        direction: 'verifier -> trust services',
      },
    },
    {
      id: 'e-tap-to-merchant',
      source: 'n-tap',
      target: 'n-merchant',
      type: 'tap-credential',
      animated: true,
      label: 'trust result',
      activeInSteps: ['tap-credential-issued', 'merchant-accepts'],
      data: {
        protocol: 'merchant or edge integration',
        payload: 'verified-agent result or scoped proof',
        direction: 'verifier -> merchant',
      },
    },
    {
      id: 'e-agent-to-merchant',
      source: 'n-agent-runtime',
      target: 'n-merchant',
      type: 'tap-credential',
      animated: true,
      label: 'checkout request',
      activeInSteps: ['merchant-accepts'],
      data: {
        protocol: 'HTTPS',
        payload: 'cart, merchant, amount, trust evidence',
        direction: 'agent -> merchant',
      },
    },
    {
      id: 'e-merchant-to-acquirer',
      source: 'n-merchant',
      target: 'n-acquirer',
      type: 'iso8583',
      animated: true,
      label: 'payment request',
      activeInSteps: ['merchant-accepts', 'acquirer-iso8583'],
      data: {
        protocol: 'PSP/acquirer API -> network authorization',
        payload: 'tokenized credential, amount, merchant context',
        direction: 'merchant -> acquirer',
      },
    },
    {
      id: 'e-acquirer-to-visa',
      source: 'n-acquirer',
      target: 'n-visa',
      type: 'iso8583',
      animated: true,
      label: 'auth metadata',
      activeInSteps: ['acquirer-iso8583', 'visanet-routes'],
      data: {
        protocol: 'existing card-network authorization path',
        payload: 'token and agent context metadata',
        direction: 'acquirer -> card network',
      },
    },
    {
      id: 'e-visa-to-issuer',
      source: 'n-visa',
      target: 'n-issuer',
      type: 'iso8583',
      animated: true,
      label: 'authorization',
      activeInSteps: ['visanet-routes', 'issuer-auth'],
      data: {
        protocol: 'existing issuer routing',
        payload: 'transaction, token, and risk context',
        direction: 'card network -> issuer',
      },
    },
    {
      id: 'e-issuer-to-visa',
      source: 'n-issuer',
      target: 'n-visa',
      type: 'funds',
      animated: true,
      label: 'response',
      activeInSteps: ['issuer-auth', 'settlement-complete'],
      data: {
        protocol: 'authorization response',
        payload: 'issuer decision and authorization metadata',
        direction: 'issuer -> card network -> acquirer',
      },
    },
  ],

  metadata: {
    totalLatency: 'not publicly specified',
    tapLatency: 'not publicly specified',
    visanetLatency: 'not publicly specified',
    issuerLatency: 'not publicly specified',
    settlementCycle: 'existing card-clearing cycle',
    tags: ['agentic-commerce', 'visa', 'trusted-agent-protocol', 'iso8583', 'passkeys', 'network-tokenization'],
    protocols: ['HTTP Message Signatures - IETF RFC 9421', 'existing card-network authorization messages', 'FIDO2 / WebAuthn passkeys'],
    standards: ['IETF RFC 9421', 'FIDO2 / WebAuthn', 'PCI DSS'],
    keyActors: ['Visa', 'Cloudflare', 'merchant', 'PSP/acquirer', 'issuer', 'consumer'],
    sources: [
      {
        label: 'Visa: What is agentic commerce?',
        url: 'https://corporate.visa.com/en/sites/visa-perspectives/innovation/what-is-agentic-commerce.html',
      },
      {
        label: 'Visa: Trusted Agent Protocol announcement',
        url: 'https://corporate.visa.com/en/sites/visa-perspectives/newsroom/visa-unveils-trusted-agent-protocol-for-ai-commerce.html',
      },
      {
        label: 'Visa Trusted Agent Protocol repository',
        url: 'https://github.com/visa/trusted-agent-protocol',
      },
      {
        label: 'RFC 9421: HTTP Message Signatures',
        url: 'https://www.rfc-editor.org/rfc/rfc9421',
      },
    ],
  },
};
